# Generated by Django 4.2.6 on 2023-11-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('sport', models.IntegerField(verbose_name='Sport')),
                ('initialDate', models.DateField(verbose_name='Initial Date')),
                ('finalDate', models.DateField(verbose_name='Final Date')),
                ('category', models.IntegerField(verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': ('Championship',),
                'verbose_name_plural': ('Championships',),
                'db_table': 'championship',
            },
        ),
    ]
