# Generated by Django 4.2.6 on 2023-11-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'verbose_name': 'Championship', 'verbose_name_plural': 'Championship'},
        ),
    ]
