# Generated by Django 4.2.7 on 2023-11-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdwardsPublicationsBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.CharField(max_length=50, verbose_name='Campeonato')),
                ('sport', models.CharField(max_length=50, verbose_name='Sport')),
                ('date', models.DateField(verbose_name='Date')),
                ('state', models.IntegerField(verbose_name='State')),
            ],
            options={
                'verbose_name': 'AdwardsPublicationsBet',
                'verbose_name_plural': 'AdwardsPublicationsBet',
                'db_table': 'adwardsPublicationsBet',
            },
        ),
    ]
