# Generated by Django 4.2.7 on 2023-11-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdwardsPublicationsBet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adwardspublicationsbet',
            old_name='campeonato',
            new_name='Championship',
        ),
    ]
