# Generated by Django 4.2.7 on 2023-11-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdwardsPublicationsBet', '0002_rename_campeonato_adwardspublicationsbet_championship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adwardspublicationsbet',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
    ]
