# Generated by Django 4.2.7 on 2023-11-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdwardsPublicationsBet', '0003_alter_adwardspublicationsbet_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adwardspublicationsbet',
            name='Championship',
            field=models.CharField(max_length=50, verbose_name='championship'),
        ),
    ]
