# Generated by Django 4.2.7 on 2023-11-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdwardsPublicationsBet', '0005_alter_adwardspublicationsbet_championship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adwardspublicationsbet',
            old_name='Championship',
            new_name='championship',
        ),
    ]
