# Generated by Django 4.2.7 on 2023-11-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raffle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='winning_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
