# Generated by Django 4.2.7 on 2023-11-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('value', models.IntegerField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Prize',
                'verbose_name_plural': 'Prize',
                'db_table': 'prize',
            },
        ),
    ]
