# Generated by Django 4.2.7 on 2023-11-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdwardsPublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raffle', models.CharField(max_length=50, verbose_name='Raffle')),
                ('date', models.DateField(verbose_name='Date')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('winnerNumber', models.IntegerField(verbose_name='WinnerNumber')),
                ('prize', models.CharField(max_length=50, verbose_name='Prize')),
            ],
            options={
                'verbose_name': 'AdwardsPublications',
                'verbose_name_plural': 'AdwardsPublications',
                'db_table': 'adwardsPublications',
            },
        ),
    ]
