# Generated by Django 4.2.7 on 2023-11-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotteryDate', models.DateField(verbose_name='Lottery Date')),
            ],
            options={
                'verbose_name': 'Lottery',
                'verbose_name_plural': 'Lottery',
                'db_table': 'lottery',
            },
        ),
    ]
